"""Generates a runnable PySpark **snapshot** notebook: source -> Lakebase (Postgres).

Async mode is a one-off snapshot. The schema & code migration plan (the same plan
Sync mode applies) creates the target tables in Lakebase Postgres; this generated
notebook reads each selected source table with Spark's named ``sqlserver``
connector (range-partitioned on the scanned primary key when possible) and streams
it straight into the plan-created table with Postgres ``COPY .. FROM STDIN`` from
every partition — the same protocol (and type fidelity) Sync mode uses, with no
staging table or ``INSERT .. SELECT CAST(..)`` double write. Tables load
concurrently on a thread pool so a multi-node cluster stays busy end to end.
Source columns Spark can't read raw (``sql_variant``, ``hierarchyid``, spatial —
UNRECOGNIZED_SQL_TYPE) are converted to text by SQL Server inside the SELECT
list, matching the ``text`` columns the plan creates for them.
Running it on Databricks (serverless or classic job compute) lets the copy scale
out beyond the in-app loader — there is no Delta landing, no synced table and no
CDC.

The generated code reads both the source and the Lakebase passwords from a
Databricks secret scope at runtime (never embedded). It's emitted as text for the
user to review, drop into a notebook/job, and run — the accelerator does not
execute it for them.

Templates are plain strings with ``__TOKEN__`` placeholders (not f-strings) so the
generated Python can contain real f-strings/braces without escaping games.
"""
from __future__ import annotations

from backend.data_migration.models import Artifact, DataGenRequest, PostLoadStatement, TableRef
from backend.schema_migration.naming import map_object, map_schema
from backend.schema_migration.trigger_sql import sanitize_trigger_sql

# --- Connection preamble injected into the generated notebook -------------------

_HEADER = '''\
# --- Source connection (Azure SQL / SQL Server) ---
HOST = "__HOST__"
PORT = __PORT__
DATABASE = "__DATABASE__"
USER = "__USER__"
# Password pulled from the Databricks secret scope at runtime (never embedded).
PASSWORD = dbutils.secrets.get(scope="__SCOPE__", key="__PWD_KEY__")

# --- Target connection (Lakebase / Postgres) ---
PG_HOST = "__PG_HOST__"
PG_PORT = __PG_PORT__
PG_DATABASE = "__PG_DATABASE__"
PG_USER = "__PG_USER__"
# Lakebase role password from the secret scope (never embedded). Alternatively,
# mint a short-lived Postgres OAuth token from the workspace identity and use it here.
PG_PASSWORD = dbutils.secrets.get(scope="__SCOPE__", key="__PG_PWD_KEY__")'''


_SNAPSHOT = '''\
# Databricks notebook source
# MAGIC %md
# MAGIC # Snapshot load — SQL Server -> Lakebase (Postgres)
# MAGIC Generated by Lakebase Express. One-off full copy of each selected table
# MAGIC into the Lakebase tables the schema & code migration plan created.
# MAGIC **Apply that plan first** (Sync mode / Schema & Code) so the target tables
# MAGIC exist, then review this notebook and Run All — on serverless or on a
# MAGIC classic job cluster (pick the compute on the job's Compute panel).
# MAGIC
# MAGIC How it loads, and why:
# MAGIC * **Postgres COPY, not INSERTs** — every Spark partition streams its rows
# MAGIC   into the target with `COPY .. FROM STDIN`, the same protocol the in-app
# MAGIC   loader uses. COPY parses values server-side against the real column types
# MAGIC   (uuid/xml/timestamptz included), so no staging table and no
# MAGIC   `INSERT .. SELECT CAST(..)` double write are needed.
# MAGIC * **Partitioned source reads** — tables whose scanned primary key is
# MAGIC   numeric/date/timestamp are range-partitioned into `NUM_PARTITIONS`
# MAGIC   concurrent JDBC reads; each partition COPYs independently.
# MAGIC * **Concurrent tables** — up to `MAX_PARALLEL_TABLES` tables load at once,
# MAGIC   keeping a multi-node cluster busy instead of walking tables one by one.
# MAGIC * **Driver-hostile types cast server-side** — columns Spark can't read
# MAGIC   (`sql_variant`, `hierarchyid`, `geography`, `geometry` fail the whole
# MAGIC   table with `UNRECOGNIZED_SQL_TYPE`) are converted to text by SQL Server
# MAGIC   in the SELECT list, matching the `text` columns the plan creates for them.
# MAGIC * **Constraints & indexes after the data** — the plan's post-data DDL
# MAGIC   (primary/foreign keys, indexes, defaults, identity, checks, triggers)
# MAGIC   lives in the companion `02_post_load_*` notebooks (one per object type:
# MAGIC   constraints, indexes, foreign keys, triggers), each a chained job task
# MAGIC   that runs once this copy finishes — so the bulk COPY never pays per-row
# MAGIC   index maintenance or FK validation. Existing foreign keys on the targets
# MAGIC   are dropped up front here (re-runs would fail the TRUNCATE otherwise) and
# MAGIC   recreated right after the copy.
# MAGIC
# MAGIC Each table is truncated right before its COPY starts, so re-running the job
# MAGIC (or just the failed tables) is always safe. If your serverless network
# MAGIC policy blocks outbound connections from Python workers, run the job on
# MAGIC classic job compute instead — that's the job's Compute panel.

# COMMAND ----------

# MAGIC %pip install psycopg[binary]

# COMMAND ----------

dbutils.library.restartPython()

# COMMAND ----------

__HEADER__

# COMMAND ----------

# --- Tuning ---
# Tables loaded concurrently; each drives its own source read + COPY streams.
MAX_PARALLEL_TABLES = 4
# Range-partitioned JDBC reads per table (used when the table has a usable
# partition column — see TABLES below). Every read partition opens one COPY
# connection, so peak Postgres connections ≈ MAX_PARALLEL_TABLES * NUM_PARTITIONS;
# keep that under the Lakebase instance's connection limit.
NUM_PARTITIONS = 8
# Rows per JDBC round trip on the source read.
FETCH_SIZE = 10000

# COMMAND ----------

# Tables to snapshot:
#   (source_schema, source_table, target_schema, target_table, partition_column)
# partition_column is the scanned primary key's leading column; None (or a
# non-numeric/date key) falls back to a single-stream read for that table.
TABLES = [
__TABLES__
]

# COMMAND ----------

import datetime
from concurrent.futures import ThreadPoolExecutor
from decimal import Decimal

import psycopg

PG_KWARGS = dict(
    host=PG_HOST, port=PG_PORT, dbname=PG_DATABASE,
    user=PG_USER, password=PG_PASSWORD, sslmode="require",
    application_name="lakebase-express-snapshot",
)

# Spark can only range-partition a JDBC read on numeric/date/timestamp columns.
_PARTITIONABLE = (int, float, Decimal, datetime.date, datetime.datetime)


# Serverless compute only allows the named sqlserver connector for reads, not the
# generic "jdbc" source, and it validates options against an allowlist — no TLS
# options like encrypt (the driver negotiates TLS by default, which Azure SQL
# enforces anyway). A fresh reader per call: .option() mutates the reader, and
# "query" and "dbtable" must never end up on the same one.
def _reader():
    return (
        spark.read.format("sqlserver")
        .option("host", HOST)
        .option("port", PORT)
        .option("database", DATABASE)
        .option("user", USER)
        .option("password", PASSWORD)
        .option("fetchsize", FETCH_SIZE)
    )


def _bounds(dbtable: str, part_col: str):
    """MIN/MAX of the partition column, or None when the probe fails or the key
    isn't range-partitionable — the table then falls back to a single-stream read."""
    try:
        row = (
            _reader()
            .option(
                "query",
                f"SELECT MIN([{part_col}]) AS lo, MAX([{part_col}]) AS hi FROM {dbtable}",
            )
            .load()
            .first()
        )
    except Exception as exc:
        print(f"   bounds probe failed on {dbtable} — single-stream read ({exc})")
        return None
    lo, hi = (row["lo"], row["hi"]) if row else (None, None)
    if lo is None or hi is None or lo == hi or not isinstance(lo, _PARTITIONABLE):
        return None
    return lo, hi


# SQL Server types Spark's reader cannot map (it fails the whole table with
# UNRECOGNIZED_SQL_TYPE, e.g. sql_variant id -156). Each is converted to text
# by SQL Server itself inside the SELECT list — matching the text columns the
# schema & code plan creates for them.
UNREADABLE_TYPES = {
    "sql_variant": "CAST({c} AS NVARCHAR(MAX)) AS {a}",
    "hierarchyid": "{c}.ToString() AS {a}",
    "geography": "{c}.STAsText() AS {a}",
    "geometry": "{c}.STAsText() AS {a}",
}


def _source_relation(src_schema: str, src_table: str) -> str:
    """The relation the read pulls from: the raw table, or — when it has columns
    Spark can't read — a subquery casting those columns to text server-side.
    Aliases keep the original column names (which the plan-created target table
    preserves), so bounds probes, partitioned reads, and the COPY column list
    all keep working against the subquery."""
    s, t = src_schema.replace("'", "''"), src_table.replace("'", "''")
    # No ORDER BY here: Spark wraps the "query" option in a derived table
    # (SPARK_GEN_SUBQ), and SQL Server rejects ORDER BY inside one. Sort client-side.
    meta = (
        _reader()
        .option(
            "query",
            "SELECT COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS "
            f"WHERE TABLE_SCHEMA = '{s}' AND TABLE_NAME = '{t}'",
        )
        .load()
        .collect()
    )
    meta = sorted(meta, key=lambda r: r["ORDINAL_POSITION"])
    if not any(r["DATA_TYPE"].lower() in UNREADABLE_TYPES for r in meta):
        return f"[{src_schema}].[{src_table}]"
    parts = []
    for r in meta:
        col = f"[{r['COLUMN_NAME']}]"
        tmpl = UNREADABLE_TYPES.get(r["DATA_TYPE"].lower())
        parts.append(tmpl.format(c=col, a=col) if tmpl else col)
    return f"(SELECT {', '.join(parts)} FROM [{src_schema}].[{src_table}]) AS src"


def read_source(src_schema: str, src_table: str, part_col: str | None):
    """Read one source table, range-partitioned on part_col when possible."""
    dbtable = _source_relation(src_schema, src_table)
    bounds = _bounds(dbtable, part_col) if part_col else None
    if bounds:
        return (
            _reader()
            .option("dbtable", dbtable)
            .option("partitionColumn", part_col)
            .option("lowerBound", str(bounds[0]))
            .option("upperBound", str(bounds[1]))
            .option("numPartitions", NUM_PARTITIONS)
            .load()
        )
    return _reader().option("dbtable", dbtable).load()


def _copy_stream(fq_target: str, col_list: str):
    """Executor-side writer: one COPY per Spark partition, straight into the
    plan-created table. psycopg adapts the native Python values and the server
    parses them against the real column types — uuid/xml/timestamptz included."""

    def write(batches):
        import psycopg  # runs on the executors
        import pyarrow as pa

        rows = 0
        with psycopg.connect(**PG_KWARGS) as pg, pg.cursor() as cur:
            with cur.copy(f"COPY {fq_target} ({col_list}) FROM STDIN") as copy:
                for batch in batches:
                    cols = [batch.column(i).to_pylist() for i in range(batch.num_columns)]
                    for row in zip(*cols):
                        copy.write_row(row)
                        rows += 1
        yield pa.record_batch([pa.array([rows], pa.int64())], names=["rows"])

    return write


def snapshot_table(src_schema, src_table, dst_schema, dst_table, part_col) -> int:
    label = f"{src_schema}.{src_table} -> {dst_schema}.{dst_table}"
    fq_target = f'"{dst_schema}"."{dst_table}"'
    print(f"-> {label} ...")
    df = read_source(src_schema, src_table, part_col)
    # Target columns keep the scanned source names, so the DataFrame's columns
    # are the COPY column list (order-independent — COPY matches by name).
    col_list = ", ".join(f'"{c}"' for c in df.columns)
    has_triggers = False
    with psycopg.connect(**PG_KWARGS) as pg, pg.cursor() as cur:
        cur.execute("SELECT to_regclass(%s)", (fq_target,))
        if cur.fetchone()[0] is None:
            raise RuntimeError(
                f"Target table {dst_schema}.{dst_table} not found — apply the schema & code plan first."
            )
        # Keep translated triggers from firing once per bulk-loaded row (the
        # COPY streams run on separate executor connections, so the disable is
        # committed here and reverted after the load).
        cur.execute(
            "SELECT EXISTS (SELECT 1 FROM pg_trigger "
            "WHERE tgrelid = %s::regclass AND NOT tgisinternal)",
            (fq_target,),
        )
        has_triggers = cur.fetchone()[0]
        if has_triggers:
            cur.execute(f"ALTER TABLE {fq_target} DISABLE TRIGGER USER")
        cur.execute(f"TRUNCATE TABLE {fq_target}")
    # Truncate committed above; the parallel COPY streams append into the empty
    # table. A failure leaves the table partial — re-running truncates it again.
    try:
        counts = df.mapInArrow(_copy_stream(fq_target, col_list), "rows long").collect()
    finally:
        if has_triggers:
            with psycopg.connect(**PG_KWARGS) as pg, pg.cursor() as cur:
                cur.execute(f"ALTER TABLE {fq_target} ENABLE TRIGGER USER")
    rows = sum(r["rows"] for r in counts)
    print(f"   ok {label}: {rows:,} rows")
    return rows


def drop_target_fks() -> list:
    """Capture + drop every FK that involves a target table (either side).

    A re-run would otherwise fail the TRUNCATEs, and the COPY would pay per-row
    FK validation. Definitions are returned so restore_target_fks() (plus the
    idempotent post-load foreign-keys task) can put them back after the load."""
    with psycopg.connect(**PG_KWARGS) as pg, pg.cursor() as cur:
        oids = []
        for _s, _t, dst_schema, dst_table, _p in TABLES:
            cur.execute("SELECT to_regclass(%s)::oid", (f'"{dst_schema}"."{dst_table}"',))
            oid = cur.fetchone()[0]
            if oid is not None:
                oids.append(oid)
        if not oids:
            return []
        cur.execute(
            "SELECT conrelid::regclass::text, conname, pg_get_constraintdef(oid) "
            "FROM pg_constraint WHERE contype = 'f' "
            "AND (conrelid = ANY(%s) OR confrelid = ANY(%s)) "
            "ORDER BY 1, 2",
            (oids, oids),
        )
        dropped = cur.fetchall()
        for tbl, name, _d in dropped:
            cur.execute(f'ALTER TABLE {tbl} DROP CONSTRAINT "{name}"')
    return dropped


def restore_target_fks(dropped) -> dict:
    """Recreate the captured FKs; failures (e.g. orphan rows) don't stop the rest."""
    failures = {}
    if not dropped:
        return failures
    with psycopg.connect(**PG_KWARGS) as pg:
        for tbl, name, definition in dropped:
            try:
                with pg.cursor() as cur:
                    cur.execute(f'ALTER TABLE {tbl} ADD CONSTRAINT "{name}" {definition}')
                pg.commit()
            except Exception as exc:
                pg.rollback()
                failures[f"FK restore {tbl} {name}"] = exc
                print(f"   FAILED restoring FK {name} on {tbl}: {exc}")
    return failures

# COMMAND ----------

print(f"Snapshotting {len(TABLES)} table(s), up to {MAX_PARALLEL_TABLES} in parallel ...")
dropped_fks = drop_target_fks()
if dropped_fks:
    print(f"Dropped {len(dropped_fks)} foreign key(s) for the load — restored afterwards.")

failures: dict[str, Exception] = {}
total_rows = 0
with ThreadPoolExecutor(max_workers=MAX_PARALLEL_TABLES) as pool:
    futures = {pool.submit(snapshot_table, *spec): spec for spec in TABLES}
    for fut, (src_schema, src_table, _s, _t, _p) in futures.items():
        try:
            total_rows += fut.result()
        except Exception as exc:
            failures[f"{src_schema}.{src_table}"] = exc
            print(f"   FAILED {src_schema}.{src_table}: {exc}")

# Restore the FKs the load dropped. The plan's own constraint/index/FK/trigger
# items are applied by the chained post-load tasks — idempotently, so the
# overlap with the restore is fine.
restore_failures = restore_target_fks(dropped_fks)

print(f"Done: {len(TABLES) - len(failures)}/{len(TABLES)} tables, {total_rows:,} rows copied.")
if failures or restore_failures:
    raise RuntimeError(
        f"{len(failures)} table(s) and {len(restore_failures)} FK restore(s) failed: "
        f"{', '.join(sorted(failures) + sorted(restore_failures))} — each table is truncated "
        "before load, so fixing the cause and re-running is safe."
    )
'''


# --- Post-load DDL notebooks (one job task per object type) -----------------------
#
# The post-data phase is split into one notebook + one job task per object type,
# chained in dependency-safe order (constraints -> indexes -> foreign keys ->
# triggers), so each type is a distinct, independently-repairable run step and
# it's obvious from the job graph exactly where a failure was.

_POST_LOAD_NB = '''\
# Databricks notebook source
# MAGIC %md
# MAGIC # Post-load — __PHASE_TITLE__
# MAGIC Generated by Lakebase Express. Applies the __PHASE_LOWER__ from the
# MAGIC migration plan to Lakebase (Postgres), **after** the `01_snapshot_load`
# MAGIC copy — so the bulk load never pays per-row index maintenance or FK
# MAGIC validation. This is one of several post-load tasks (one per object type),
# MAGIC chained in dependency order: constraints → indexes → foreign keys → triggers.
# MAGIC
# MAGIC Every statement is idempotent (conditional DO blocks / `IF NOT EXISTS` /
# MAGIC `CREATE OR REPLACE`) and runs in its own transaction: one failure never
# MAGIC blocks the rest, each item prints `[n/N] ok|FAILED` as it goes, and the run
# MAGIC fails at the end with the list of failed items — fix (or edit in the plan)
# MAGIC and re-run this task alone; already-applied items are skipped.

# COMMAND ----------

# MAGIC %pip install psycopg[binary]

# COMMAND ----------

dbutils.library.restartPython()

# COMMAND ----------

__PG_HEADER__

# COMMAND ----------

# This task's statements, in apply order: (name, sql).
POST_LOAD = [
__POST_LOAD__
]

# COMMAND ----------

import time

import psycopg

PG_KWARGS = dict(
    host=PG_HOST, port=PG_PORT, dbname=PG_DATABASE,
    user=PG_USER, password=PG_PASSWORD, sslmode="require",
    application_name="lakebase-express-post-load",
)

PHASE = "__PHASE_TITLE__"
failures: dict[str, Exception] = {}
if not POST_LOAD:
    print(f"Nothing to apply for {PHASE}.")
else:
    total = len(POST_LOAD)
    print(f"Applying {total} statement(s) — {PHASE} ...")
    with psycopg.connect(**PG_KWARGS) as pg:
        for i, (name, sql) in enumerate(POST_LOAD, start=1):
            t0 = time.perf_counter()
            try:
                with pg.cursor() as cur:
                    cur.execute(sql)
                pg.commit()
                print(f"[{i}/{total}] ok     {name} ({(time.perf_counter() - t0) * 1000:.0f} ms)")
            except Exception as exc:
                pg.rollback()
                failures[name] = exc
                print(f"[{i}/{total}] FAILED {name}: {exc}")

    print(f"Done ({PHASE}): {total - len(failures)}/{total} applied, {len(failures)} failed.")

if failures:
    detail = "\\n".join(f"  - {name}: {exc}" for name, exc in failures.items())
    raise RuntimeError(
        f"{len(failures)} {PHASE} statement(s) failed:\\n{detail}\\n"
        "Every statement is idempotent — fix the SQL (or edit it in the migration "
        "plan) and re-run this task alone; already-applied items are skipped."
    )
'''


# Post-load phases, in dependency-safe apply order. Each maps the plan's post-data
# ObjectKinds to one notebook + one job task, created only when it has statements.
# (schema_number, task_key, title, {plan kinds}). Constraints (which include the
# PKs/unique indexes) come before foreign keys that reference them.
_POST_LOAD_PHASES: list[tuple[str, str, set[str]]] = [
    ("constraints", "Constraints (primary keys, defaults, identity, checks)", {"constraint"}),
    ("indexes", "Indexes", {"index"}),
    ("foreign_keys", "Foreign keys", {"foreign_key"}),
    ("triggers", "Triggers", {"trigger"}),
]


# Lakebase-only preamble for the post-load DDL notebook (no source connection —
# the post-data phase only talks to Postgres).
_PG_HEADER = '''\
# --- Target connection (Lakebase / Postgres) ---
PG_HOST = "__PG_HOST__"
PG_PORT = __PG_PORT__
PG_DATABASE = "__PG_DATABASE__"
PG_USER = "__PG_USER__"
# Lakebase role password from the secret scope (never embedded).
PG_PASSWORD = dbutils.secrets.get(scope="__SCOPE__", key="__PG_PWD_KEY__")'''


def _render_pg_header(req: DataGenRequest) -> str:
    return (
        _PG_HEADER.replace("__SCOPE__", req.secret_scope)
        .replace("__PG_HOST__", req.lakebase_host)
        .replace("__PG_PORT__", str(req.lakebase_port))
        .replace("__PG_DATABASE__", req.lakebase_database)
        .replace("__PG_USER__", req.lakebase_user)
        .replace("__PG_PWD_KEY__", req.lakebase_password_secret_key)
    )


def _render_header(req: DataGenRequest) -> str:
    return (
        _HEADER.replace("__HOST__", req.host)
        .replace("__PORT__", str(req.port))
        .replace("__DATABASE__", req.database)
        .replace("__USER__", req.username)
        # Both passwords are read from the one project secret scope.
        .replace("__SCOPE__", req.secret_scope)
        .replace("__PWD_KEY__", req.password_secret_key)
        .replace("__PG_HOST__", req.lakebase_host)
        .replace("__PG_PORT__", str(req.lakebase_port))
        .replace("__PG_DATABASE__", req.lakebase_database)
        .replace("__PG_USER__", req.lakebase_user)
        .replace("__PG_PWD_KEY__", req.lakebase_password_secret_key)
    )


def _snapshot_row(t: TableRef, target_schema: str, identifier_case="lowercase") -> str:
    """One TABLES entry, mapping source names to their Lakebase targets (matching
    the plan). The scanned primary key's leading column rides along as the
    partition-column candidate for the range-partitioned read."""
    dst_schema = map_schema(t.schema_name, target_schema, identifier_case)
    dst_table = map_object(t.table_name, identifier_case)
    part = f'"{t.primary_key[0]}"' if t.primary_key else "None"
    return f'    ("{t.schema_name}", "{t.table_name}", "{dst_schema}", "{dst_table}", {part})'


def _post_load_rows(statements: list[PostLoadStatement]) -> str:
    """POST_LOAD entries for one phase. repr() keeps arbitrary SQL (quotes, $$
    bodies, newlines) a valid Python literal. Trigger SQL is sanitized here — at
    emit time — so a stale/hand-edited plan (schema-qualified trigger name, no
    OR REPLACE) still applies cleanly regardless of when it was built."""
    rows = []
    for s in statements:
        if not s.sql.strip():
            continue
        sql = sanitize_trigger_sql(s.sql) if s.kind == "trigger" else s.sql
        rows.append(f"    ({s.name!r},\n     {sql!r})")
    return ",\n".join(rows)


def _snapshot(req: DataGenRequest) -> Artifact:
    rows = ",\n".join(
        _snapshot_row(t, req.target_schema, req.identifier_case) for t in req.tables
    )
    code = _SNAPSHOT.replace("__HEADER__", _render_header(req)).replace("__TABLES__", rows)
    return Artifact(
        name="Snapshot load (PySpark)",
        filename="01_snapshot_load.py",
        language="python",
        description="Parallel full copy of each selected table from the source straight into the "
        "Lakebase Postgres tables the schema & code plan created, via Postgres COPY.",
        code=code,
    )


def _post_load_notebook(
    req: DataGenRequest, seq: int, task_key: str, title: str, statements: list[PostLoadStatement]
) -> Artifact:
    code = (
        _POST_LOAD_NB.replace("__PG_HEADER__", _render_pg_header(req))
        .replace("__POST_LOAD__", _post_load_rows(statements))
        # Title first — it also appears inside __PHASE_LOWER__'s source line.
        .replace("__PHASE_TITLE__", title)
        .replace("__PHASE_LOWER__", title[0].lower() + title[1:])
    )
    return Artifact(
        name=f"Post-load — {title}",
        filename=f"{seq:02d}_post_load_{task_key}.py",
        language="python",
        description=f"Applies the plan's {title.lower()} after the snapshot — one idempotent "
        "statement per transaction, with per-item progress; a distinct job task so failures "
        "surface per type and can be repaired alone.",
        code=code,
    )


def post_load_artifacts(req: DataGenRequest) -> list[Artifact]:
    """One post-load notebook per object type that has statements, in the order
    the job chains them (constraints → indexes → foreign keys → triggers). The
    task_key is the artifact filename stem, which job_offload turns into the job
    task graph."""
    arts: list[Artifact] = []
    seq = 2  # 01_snapshot_load is the first notebook
    for task_key, title, kinds in _POST_LOAD_PHASES:
        stmts = [s for s in req.post_load_sql if s.kind in kinds and s.sql.strip()]
        if not stmts:
            continue
        arts.append(_post_load_notebook(req, seq, task_key, title, stmts))
        seq += 1
    return arts


def generate(req: DataGenRequest) -> list[Artifact]:
    """Async-mode notebooks: the PySpark snapshot loader first, then one post-load
    DDL notebook per object type (constraints, indexes, foreign keys, triggers) —
    each a separate, dependency-chained job task."""
    return [_snapshot(req), *post_load_artifacts(req)]
