import { useEffect, useMemo, useRef, useState } from "react";
import { api, type ParityStatus, type QueryComparison, type QueryParityRunState, type SideResult, type SyntheticQuery } from "../api";
import type { MigrationState } from "../App";

interface Props {
  state: MigrationState;
  setState: React.Dispatch<React.SetStateAction<MigrationState>>;
  goConnection: () => void;
  goAssessment: () => void;
  fmEndpoint?: string;
}

const STATUS_META: Record<ParityStatus, { label: string; badge: string }> = {
  match: { label: "match", badge: "ok" },
  mismatch: { label: "mismatch", badge: "warn" },
  error: { label: "error", badge: "err" },
};
const STATUS_ORDER: ParityStatus[] = ["mismatch", "error", "match"];

type Tone = "ok" | "warn" | "err";
const VERDICT: Record<Tone, { title: string; desc: string }> = {
  ok: { title: "Consistent", desc: "Every synthetic query returned identical results on source and Lakebase." },
  warn: { title: "Mostly consistent", desc: "Most queries matched, but some returned different results or failed to run — review below." },
  err: { title: "Inconsistent", desc: "Many queries disagree between source and Lakebase — investigate the failures below." },
};

/** Post-Migration Query Parity: an independent module that asks the AI to write
 *  synthetic read-only queries over the migrated schema, runs each against both
 *  the source and Lakebase, and compares row count, result format, and
 *  performance — so the user can trust the migration preserved query behaviour. */
export default function QueryParityModule({ state, setState, goConnection, goAssessment, fmEndpoint }: Props) {
  const conn = state.connection;
  const report = state.queryParity;
  const hasConn = !!conn?.host && !!state.lakebase?.host;
  const tables = state.report?.tables ?? [];
  const hasSchema = tables.length > 0;

  // The queries the user is about to run — generated by the AI, then editable.
  const [queries, setQueries] = useState<SyntheticQuery[]>([]);
  const [count, setCount] = useState(5);
  const [genBusy, setGenBusy] = useState(false);
  const [genErr, setGenErr] = useState<string | null>(null);

  const [runId, setRunId] = useState<string | null>(null);
  const [run, setRun] = useState<QueryParityRunState | null>(null);
  const [runErr, setRunErr] = useState<string | null>(null);
  const pollRef = useRef(true);
  // Held in a ref so the poll effect can save the report without taking
  // `setState` as a dependency — see the effect below.
  const setStateRef = useRef(setState);
  setStateRef.current = setState;

  // The LLM behind generation: the Settings override, or the server default.
  const [defaultEndpoint, setDefaultEndpoint] = useState("");
  useEffect(() => { api.listFmEndpoints().then((r) => setDefaultEndpoint(r.default)).catch(() => {}); }, []);
  const llm = fmEndpoint || defaultEndpoint;

  const running = run?.status === "running";

  // Poll until the run stops. Depends on runId ALONE — including `setState`
  // (rebuilt on every App render) re-ran this effect when the finished report
  // was saved, spawning another poll loop that saved again, forever.
  useEffect(() => {
    if (!runId) return;
    pollRef.current = true;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const tick = async () => {
      try {
        const r = await api.parityRunStatus(runId);
        if (!pollRef.current) return;
        setRun(r);
        if (r.status === "running") timer = setTimeout(tick, 1000);
        else if (r.status === "success" && r.report) {
          setStateRef.current((s) => ({ ...s, queryParity: r.report! }));
        }
      } catch (e) {
        if (pollRef.current) setRunErr((e as Error).message);
      }
    };
    tick();
    return () => {
      pollRef.current = false;
      if (timer) clearTimeout(timer);
    };
  }, [runId]);

  async function generate() {
    setGenBusy(true);
    setGenErr(null);
    try {
      const res = await api.generateParityQueries({
        tables,
        target_schema: state.targetSchema,
        identifier_case: state.identifierCase,
        count,
        endpoint: fmEndpoint || undefined,
      });
      if (!res.success) {
        setGenErr(res.error || "Could not generate queries — pick a working Foundation Model endpoint in Settings.");
      } else {
        setQueries(res.queries);
      }
    } catch (e) {
      setGenErr((e as Error).message);
    } finally {
      setGenBusy(false);
    }
  }

  async function run_() {
    if (!conn || !state.lakebase || !queries.length) return;
    setRunErr(null);
    setRun(null);
    try {
      const { run_id } = await api.startParityRun({
        source: conn,
        lakebase: state.lakebase,
        target_schema: state.targetSchema,
        identifier_case: state.identifierCase,
        queries,
      });
      setRunId(run_id);
    } catch (e) {
      setRunErr((e as Error).message);
    }
  }

  function updateQuery(id: string, patch: Partial<SyntheticQuery>) {
    setQueries((qs) => qs.map((q) => (q.id === id ? { ...q, ...patch } : q)));
  }
  function removeQuery(id: string) {
    setQueries((qs) => qs.filter((q) => q.id !== id));
  }

  return (
    <div className="stack">
      {!hasConn && (
        <div className="card">
          <h2>Connections not configured</h2>
          <p className="muted">Query parity runs each query against the live source and the Lakebase target — set up and test both connections first.</p>
          <div className="actions"><button className="btn btn--primary" onClick={goConnection}>Go to Connections &amp; Target</button></div>
        </div>
      )}

      <section className="card">
        <div className="card__head">
          <h2>Synthetic query parity</h2>
          {report && <span className="muted">last run {new Date(report.generated_at).toLocaleString()}</span>}
        </div>
        <p className="muted">
          The AI writes a batch of read-only queries over the migrated schema — each expressed in
          both T-SQL and PostgreSQL — then runs every one against the source and Lakebase and compares
          the results: <strong>row count</strong>, <strong>result format</strong> (columns and values),
          and <strong>performance</strong>. Review and edit the generated queries before running them.
        </p>

        {!hasSchema ? (
          <div className="banner banner--err" style={{ marginTop: 4 }}>
            No scanned schema yet — run the{" "}
            <button className="link" onClick={goAssessment}>Assessment</button>{" "}
            first so there are tables to generate queries against.
          </div>
        ) : (
          <>
            <div className="parity-gen">
              <div className="parity-gen__field">
                <label htmlFor="qp-count">How many queries</label>
                <input
                  id="qp-count"
                  type="number"
                  min={1}
                  max={50}
                  value={count}
                  disabled={genBusy || running}
                  onChange={(e) => setCount(Math.max(1, Math.min(50, Number(e.target.value) || 1)))}
                />
              </div>
              <button className="btn btn--primary parity-gen__go" disabled={genBusy || running} onClick={generate}>
                {genBusy ? "Generating…" : <><span className="ai-spark" aria-hidden>✦</span> {queries.length ? "Regenerate queries" : "Generate queries"}</>}
              </button>
              {llm && (
                <span className="parity-gen__model">
                  <span className="parity-gen__model-label">Model</span>
                  <span className="sbadge sbadge--ai" title="The Foundation Model serving endpoint behind query generation — change it in Settings.">
                    {llm}
                  </span>
                </span>
              )}
            </div>
            {genErr && <div className="banner banner--err">{genErr}</div>}
          </>
        )}
      </section>

      {queries.length > 0 && (
        <section className="card">
          <div className="card__head">
            <h3>Queries to run</h3>
            <span className="muted">{queries.length} quer{queries.length === 1 ? "y" : "ies"} · read-only</span>
          </div>
          <p className="muted">Edit any query before running — both sides must stay semantically equivalent for the comparison to be meaningful.</p>
          <div className="plangroups">
            {queries.map((q, i) => (
              <QueryEditor key={q.id} index={i} query={q} disabled={running} onChange={updateQuery} onRemove={removeQuery} />
            ))}
          </div>
          <div className="actions">
            <button className="btn btn--primary" disabled={!hasConn || running || !queries.length} onClick={run_}>
              {running ? "Running…" : `Run parity on ${queries.length} quer${queries.length === 1 ? "y" : "ies"}`}
            </button>
          </div>
          {runErr && <div className="banner banner--err">{runErr}</div>}
          {run && (running || run.status === "failed") && <RunProgress run={run} />}
        </section>
      )}

      {report && !running && (
        <>
          <ReportHero report={report} />
          <ComparisonList report={report} />
        </>
      )}
    </div>
  );
}

// --- Query editor -------------------------------------------------------------------

function QueryEditor({ index, query, disabled, onChange, onRemove }: {
  index: number;
  query: SyntheticQuery;
  disabled: boolean;
  onChange: (id: string, patch: Partial<SyntheticQuery>) => void;
  onRemove: (id: string) => void;
}) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`planrow ${open ? "is-open" : ""}`}>
      <div className="planrow__headwrap">
        <button className="planrow__head" onClick={() => setOpen(!open)}>
          <Caret open={open} />
          <span className="navnum navnum--hub">{index + 1}</span>
          <span className="tag tag--kind">{query.category}</span>
          <span className="planrow__name">{query.title}</span>
        </button>
        {!disabled && (
          <button className="link planrow__remove" onClick={() => onRemove(query.id)}>remove</button>
        )}
      </div>
      {open && (
        <div className="planrow__body">
          {query.intent && <div className="finding__detail">{query.intent}</div>}
          <div className="fixgrid">
            <div className="fixpane">
              <div className="code fixpane__frame">
                <div className="code__bar"><span className="code__lang">Source · T-SQL</span></div>
                <textarea
                  className="sqlbox fixpane__editor"
                  value={query.source_sql}
                  disabled={disabled}
                  onChange={(e) => onChange(query.id, { source_sql: e.target.value })}
                />
              </div>
            </div>
            <div className="fixpane">
              <div className="code fixpane__frame">
                <div className="code__bar"><span className="code__lang">Target · PostgreSQL</span></div>
                <textarea
                  className="sqlbox fixpane__editor"
                  value={query.target_sql}
                  disabled={disabled}
                  onChange={(e) => onChange(query.id, { target_sql: e.target.value })}
                />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// --- Run progress -------------------------------------------------------------------

function RunProgress({ run }: { run: QueryParityRunState }) {
  const counting = run.queries_total > 0;
  const pct =
    run.status !== "running" ? 100
    : counting ? Math.max(6, (run.queries_done / Math.max(1, run.queries_total)) * 100)
    : 12;
  const failed = run.status === "failed";
  return (
    <div className="phasebox">
      <div className="prog__row">
        <span className="prog__name">{run.phase}</span>
        <span className="prog__count">{counting ? `${run.queries_done} / ${run.queries_total} queries` : ""}</span>
        <span className={`sbadge sbadge--${failed ? "err" : "ai"}`}>{failed ? "failed" : "running"}</span>
      </div>
      <div className="bar">
        <div className={`bar__fill bar__fill--${failed ? "failed" : "running"}`} style={{ width: `${pct}%` }} />
      </div>
      {run.current && !failed && <p className="muted" style={{ margin: "8px 0 0" }}>Running {run.current}…</p>}
      {run.error && <div className="banner banner--err">{run.error}</div>}
    </div>
  );
}

// --- Report hero --------------------------------------------------------------------

function ReportHero({ report }: { report: NonNullable<MigrationState["queryParity"]> }) {
  const tone: Tone = report.parity_score === 100 ? "ok" : report.parity_score >= 70 ? "warn" : "err";
  const verdict = VERDICT[tone];
  // Overall performance: how the target's total time compares to the source's.
  const perf = performanceLabel(report.source_total_ms, report.target_total_ms);
  return (
    <section className="card report-hero">
      <MatchDonut value={report.parity_score} tone={tone} />
      <div className="report-hero__main">
        <span className={`verdict-chip verdict-chip--${tone}`}>{verdict.title}</span>
        <p className="muted report-hero__desc">{verdict.desc}</p>
        <div className="statgrid statgrid--4">
          <Stat value={report.matched} label="Matched" />
          <Stat value={report.mismatched} label="Mismatched" alert={report.mismatched > 0} />
          <Stat value={report.errored} label="Errored" alert={report.errored > 0} />
          <Stat value={report.total} label="Queries run" />
        </div>
        <p className="muted" style={{ marginTop: 12 }}>
          {report.source_database} → {report.target_database}
          {report.source_total_ms > 0 && (
            <>
              {" "}· total execution: {report.source_total_ms.toLocaleString()} ms source /{" "}
              {report.target_total_ms.toLocaleString()} ms target
              {perf && <> · <strong>{perf}</strong></>}
            </>
          )}
        </p>
      </div>
    </section>
  );
}

/** Human summary of how the target's total time compares to the source's. */
function performanceLabel(sourceMs: number, targetMs: number): string {
  if (sourceMs <= 0 || targetMs <= 0) return "";
  if (targetMs < sourceMs) return `Lakebase ${(sourceMs / targetMs).toFixed(1)}× faster overall`;
  if (targetMs > sourceMs) return `Lakebase ${(targetMs / sourceMs).toFixed(1)}× slower overall`;
  return "Comparable performance";
}

function Stat({ value, label, alert }: { value: number; label: string; alert?: boolean }) {
  return (
    <div className="stat">
      <div className="stat__text">
        <div className="stat__value" style={alert ? { color: "var(--err)" } : undefined}>{value.toLocaleString()}</div>
        <div className="stat__label">{label}</div>
      </div>
    </div>
  );
}

function MatchDonut({ value, tone }: { value: number; tone: Tone }) {
  const r = 52;
  const circ = 2 * Math.PI * r;
  const pct = Math.max(0, Math.min(100, value));
  const offset = circ * (1 - pct / 100);
  const color = tone === "ok" ? "var(--ok)" : tone === "warn" ? "var(--warn)" : "var(--err)";
  return (
    <div className="donut">
      <svg viewBox="0 0 120 120" width="120" height="120">
        <circle cx="60" cy="60" r={r} fill="none" stroke="var(--border)" strokeWidth="10" />
        <circle
          cx="60" cy="60" r={r} fill="none" stroke={color} strokeWidth="10" strokeLinecap="round"
          strokeDasharray={circ} strokeDashoffset={offset} transform="rotate(-90 60 60)"
          style={{ transition: "stroke-dashoffset .6s ease" }}
        />
      </svg>
      <div className="donut__center">
        <div className="donut__value">{value}%</div>
        <div className="donut__label">parity</div>
      </div>
    </div>
  );
}

// --- Comparison list ----------------------------------------------------------------

function ComparisonList({ report }: { report: NonNullable<MigrationState["queryParity"]> }) {
  const [active, setActive] = useState<Set<ParityStatus>>(new Set());
  const [openId, setOpenId] = useState<string | null>(null);

  const counts = useMemo(() => {
    const c: Record<ParityStatus, number> = { match: 0, mismatch: 0, error: 0 };
    report.comparisons.forEach((cmp) => { c[cmp.status] += 1; });
    return c;
  }, [report.comparisons]);

  const shown = report.comparisons.filter((c) => active.size === 0 || active.has(c.status));
  const issues = report.mismatched + report.errored;

  const toggle = (s: ParityStatus) =>
    setActive((prev) => {
      const next = new Set(prev);
      next.has(s) ? next.delete(s) : next.add(s);
      return next;
    });

  return (
    <section className="card">
      <div className="card__head">
        <h3>Query-by-query results</h3>
        <span className="muted">
          {issues === 0 ? "no discrepancies" : `${issues} quer${issues === 1 ? "y" : "ies"} to review`}
          {active.size > 0 && <> · <button className="link" onClick={() => setActive(new Set())}>clear filter</button></>}
        </span>
      </div>

      {issues === 0 && (
        <div className="success-state" style={{ marginBottom: 14 }}>
          <span className="success-state__icon">✓</span>
          <div>
            <strong>Source and Lakebase returned identical results</strong>
            <p className="muted">Every synthetic query matched on row count and result format.</p>
          </div>
        </div>
      )}

      <div className="plantools">
        <div className="chipbar">
          {STATUS_ORDER.map((s) => (
            <button
              key={s}
              className={`chip ${active.has(s) ? "is-active" : ""}`}
              disabled={!counts[s]}
              onClick={() => toggle(s)}
            >
              {STATUS_META[s].label} <span className="chip__n">{counts[s]}</span>
            </button>
          ))}
        </div>
      </div>

      <div className="plangroup__items" style={{ borderTop: "1px solid var(--border)" }}>
        {shown.length === 0 && <p className="muted plan-empty">No queries match the current filter.</p>}
        {shown.map((cmp) => (
          <ComparisonRow
            key={cmp.query.id}
            cmp={cmp}
            open={openId === cmp.query.id}
            onToggle={() => setOpenId(openId === cmp.query.id ? null : cmp.query.id)}
          />
        ))}
      </div>
    </section>
  );
}

function ComparisonRow({ cmp, open, onToggle }: { cmp: QueryComparison; open: boolean; onToggle: () => void }) {
  const meta = STATUS_META[cmp.status];
  const speed = speedLabel(cmp);
  return (
    <div className={`planrow ${open ? "is-open" : ""}`}>
      <button className="planrow__head" onClick={onToggle}>
        <Caret open={open} />
        <span className="tag tag--kind">{cmp.query.category}</span>
        <span className="planrow__name">{cmp.query.title}</span>
        {cmp.status !== "error" && (
          <span className="trow__rows">
            {cmp.source.row_count.toLocaleString()} → {cmp.target.row_count.toLocaleString()} rows
          </span>
        )}
        {speed && <span className={`sbadge sbadge--${speed.badge}`}>{speed.label}</span>}
        <span className={`sbadge sbadge--${meta.badge}`}>{meta.label}</span>
      </button>
      {open && (
        <div className="planrow__body">
          <div className="finding__detail">{cmp.detail}</div>

          {cmp.status === "mismatch" && cmp.mismatch_columns.length > 0 && (
            <div className="qp-diffcols">
              <span className="qp-diffcols__label">Columns that differ:</span>
              {cmp.mismatch_columns.map((c) => (
                <span key={c} className="qp-diffcols__chip">{c}</span>
              ))}
            </div>
          )}

          <div className="statgrid" style={{ marginTop: 12 }}>
            <SideCard title="Source" side={cmp.source} />
            <SideCard title="Target (Lakebase)" side={cmp.target} />
            <div className="stat">
              <div className="stat__text">
                <div className="stat__value">{speed ? speed.detail : "—"}</div>
                <div className="stat__label">Performance</div>
              </div>
            </div>
          </div>

          <ResultPreview cmp={cmp} />

          <div className="fixgrid" style={{ marginTop: 12 }}>
            <QueryPane title="Source · T-SQL" sql={cmp.query.source_sql} error={cmp.source.error} />
            <QueryPane title="Target · PostgreSQL" sql={cmp.query.target_sql} error={cmp.target.error} />
          </div>
        </div>
      )}
    </div>
  );
}

// --- Result preview (side-by-side grids) --------------------------------------------

/** The two result sets shown side by side. On a mismatch, differing cells are
 *  highlighted and rows returned by only one side are flagged, so the user can
 *  see exactly what changed rather than reading a summary. */
function ResultPreview({ cmp }: { cmp: QueryComparison }) {
  // Nothing to show if a side failed (the SQL panes carry the error instead).
  if (!cmp.source.ok || !cmp.target.ok) return null;
  const hasRows = cmp.source.preview_rows.length > 0 || cmp.target.preview_rows.length > 0;
  if (!hasRows) return null;

  const isMismatch = cmp.status === "mismatch";
  // Which cells differ (by position) and which rows are one-side-only. Positions
  // are shared across the two grids because the backend compares positionally.
  const diffCells = new Map<number, Set<number>>();
  const sourceOnly = new Set<number>();
  const targetOnly = new Set<number>();
  for (const d of cmp.row_diffs) {
    if (d.kind === "value") {
      const cols = new Set<number>();
      const n = Math.min(d.source_cells.length, d.target_cells.length);
      for (let j = 0; j < n; j++) if (d.source_cells[j] !== d.target_cells[j]) cols.add(j);
      diffCells.set(d.row_index, cols);
    } else if (d.kind === "source_only") {
      sourceOnly.add(d.row_index);
    } else if (d.kind === "target_only") {
      targetOnly.add(d.row_index);
    }
  }

  const truncated = cmp.source.truncated || cmp.target.truncated;

  return (
    <div className="qp-preview">
      <div className="qp-preview__head">
        <span className="qp-preview__title">Result preview</span>
        {isMismatch && (
          <span className="qp-preview__legend">
            <span className="qp-swatch qp-swatch--diff" /> differing value
            <span className="qp-swatch qp-swatch--only" /> row on one side only
          </span>
        )}
      </div>
      <div className="qp-grid2">
        <PreviewTable
          label="Source"
          side={cmp.source}
          diffCells={diffCells}
          onlyRows={sourceOnly}
          highlight={isMismatch}
        />
        <PreviewTable
          label="Target (Lakebase)"
          side={cmp.target}
          diffCells={diffCells}
          onlyRows={targetOnly}
          highlight={isMismatch}
        />
      </div>
      {truncated && (
        <p className="muted qp-preview__note">
          Showing the first {Math.max(cmp.source.preview_rows.length, cmp.target.preview_rows.length)} rows —
          the full result was compared, but the preview is capped.
        </p>
      )}
    </div>
  );
}

function PreviewTable({ label, side, diffCells, onlyRows, highlight }: {
  label: string;
  side: SideResult;
  diffCells: Map<number, Set<number>>;
  onlyRows: Set<number>;
  highlight: boolean;
}) {
  return (
    <div className="qp-tablecard">
      <div className="qp-tablecard__head">{label} · {side.row_count.toLocaleString()} rows</div>
      <div className="qp-table-wrap">
        <table className="qp-table">
          <thead>
            <tr>
              <th className="qp-idx">#</th>
              {side.column_names.map((c, j) => <th key={j}>{c}</th>)}
            </tr>
          </thead>
          <tbody>
            {side.preview_rows.map((row, r) => {
              const only = highlight && onlyRows.has(r);
              const cols = diffCells.get(r);
              return (
                <tr key={r} className={only ? "qp-row--only" : undefined}>
                  <td className="qp-idx">{r + 1}</td>
                  {row.map((cell, j) => (
                    <td key={j} className={highlight && cols?.has(j) ? "qp-cell--diff" : undefined}>
                      {cell === "∅" ? <span className="qp-null">NULL</span> : cell}
                    </td>
                  ))}
                </tr>
              );
            })}
            {side.preview_rows.length === 0 && (
              <tr><td className="qp-idx" colSpan={side.column_names.length + 1}>no rows</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function SideCard({ title, side }: { title: string; side: SideResult }) {
  return (
    <div className="stat">
      <div className="stat__text">
        <div className="stat__value" style={side.ok ? undefined : { color: "var(--err)" }}>
          {side.ok ? `${side.row_count.toLocaleString()} rows` : "failed"}
        </div>
        <div className="stat__label">
          {title}
          {side.ok && <> · {side.duration_ms.toLocaleString()} ms · {side.column_names.length} col{side.column_names.length === 1 ? "" : "s"}</>}
        </div>
      </div>
    </div>
  );
}

function QueryPane({ title, sql, error }: { title: string; sql: string; error?: string | null }) {
  return (
    <div className="fixpane">
      <div className="code fixpane__frame">
        <div className="code__bar"><span className="code__lang">{title}</span></div>
        <pre className="code__body fixpane__code">{sql}</pre>
      </div>
      {error && <div className="banner banner--err" style={{ marginTop: 8 }}>{error}</div>}
    </div>
  );
}

/** Compact speedup label for a row: which side ran faster, and by how much. */
function speedLabel(cmp: QueryComparison): { label: string; detail: string; badge: string } | null {
  if (!cmp.source.ok || !cmp.target.ok || cmp.speedup_ratio == null) return null;
  const ratio = cmp.speedup_ratio; // target_ms / source_ms
  if (ratio < 1) {
    const x = (1 / ratio).toFixed(1);
    return { label: `${x}× faster`, detail: `${x}× faster on Lakebase`, badge: "ok" };
  }
  if (ratio > 1) {
    const x = ratio.toFixed(1);
    return { label: `${x}× slower`, detail: `${x}× slower on Lakebase`, badge: "warn" };
  }
  return { label: "same speed", detail: "Comparable", badge: "info" };
}

function Caret({ open }: { open: boolean }) {
  return (
    <svg className={`caret ${open ? "caret--open" : ""}`} viewBox="0 0 24 24" width="14" height="14"
         fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
      <path d="m9 6 6 6-6 6" />
    </svg>
  );
}
